import localFont from "next/font/local";
import "./globals.css";
import Provider from "@/utils/provider";
import Nav from "@/components/nav";

const manropeBold = localFont({
  src: "./fonts/Manrope-Bold.ttf",
  variable: "--font-manropeBold",
  weight: "100 900",
});
const manrope = localFont({
  src: "./fonts/Manrope-Regular.ttf",
  variable: "--font-manrope",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} ${manropeBold.variable} antialiased`}
      >
        <Provider>
          <Nav />
          {children}
        </Provider>
      </body>
    </html>
  );
}
